name: Trigger BKfoederaleArchitektur DocFX

on:
  push:
    branches:
      - main  # oder dein Branch

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger DocFX Build in BKfoederaleArchitektur
        run: |
          curl -X POST https://api.github.com/repos/Ximiq-AG/BKfoederaleArchitektur/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            -d '{"event_type":"trigger-docfx"}'
